name = "personal-site-next-testing"
main = "./worker/index.ts"
compatibility_date = "2026-02-16"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
not_found_handling = "none"

[[r2_buckets]]
binding = "GALLERY_BUCKET"
bucket_name = "gallery-photos"
